// Code generated by 'go generate'; DO NOT EDIT.
// 2021-06-11 21:33:11.9028975 +0200 CEST m=+0.003772501

// Package currencies provides a set of predefined ISO 4217
// three-letter alphabetic currency codes generated from data from
// https://www.currency-iso.org/en/home/tables/table-a1.html.
package currencies

import "fmt"

// Currency is an ISO 4217 three-letter alphabetic code for the representation of currencies.
type Currency string

//nolint:lll
const (
	EUR = Currency("EUR") // Euro (€).
	EUX = Currency("EUX") // Euro cent, 1⁄100 of EUR.
	USD = Currency("USD") // US dollar ($).
	USX = Currency("USX") // US cent (¢), 1⁄100 of USD.
	GBP = Currency("GBP") // Pound sterling (£).
	GBX = Currency("GBX") // Penny sterling (p), ​1⁄100 of a pound, but historically was 1⁄240 of a pound (old penny sterling).
	ZAR = Currency("ZAR") // South African rand (R).
	ZAC = Currency("ZAC") // South African cent (c), 1⁄100 of a rand.
	CHF = Currency("CHF") // Swiss franc (Fr).
	CAD = Currency("CAD") // Canadian dollar (C$).
	AUD = Currency("AUD") // Australian dollar (A$).
	NZD = Currency("NZD") // New Zeeland dollar ($).
	DKK = Currency("DKK") // Danish krone (kr).
	SEK = Currency("SEK") // Swedish krona (kr).
	NOK = Currency("NOK") // Norwegian krone (kr).
	ISK = Currency("ISK") // Icelandic krona (kr, Íkr).
	CZK = Currency("CZK") // Czech koruna (Kč).
	PLN = Currency("PLN") // Poland zloty (zł).
	HUF = Currency("HUF") // Hungary forint (Ft).
	RON = Currency("RON") // Romanian new leu (leu).
	MDL = Currency("MDL") // Moldovan leu (L, leu).
	RUB = Currency("RUB") // Russian rouble (₽).
	UAH = Currency("UAH") // Ukraine hryvnia (₴, since 2004).
	BYR = Currency("BYR") // Belarusian ruble (Br).
	BGN = Currency("BGN") // Bulgarian lev (лв).
	BAM = Currency("BAM") // Bosnia and Herzegovina convertible mark (KM).
	HRK = Currency("HRK") // Croatian kuna (kn).
	MKD = Currency("MKD") // Macedonian denar (den, ден).
	RSD = Currency("RSD") // Serbian dinar (din, дин).
	ALL = Currency("ALL") // Albanian lek (L).
	TRY = Currency("TRY") // Turkish new lira (TL, ₺).
	ILS = Currency("ILS") // Israeli new sheqel (₪).
	AMD = Currency("AMD") // Armenian dram (֏).
	AZN = Currency("AZN") // Azerbaijani manat (₼).
	GEL = Currency("GEL") // Georgian lari (₾, ლ).
	KGS = Currency("KGS") // Kyrgyzstani som.
	KZT = Currency("KZT") // Kazakhstani tenge (₸).
	TJS = Currency("TJS") // Tajikistani somoni (SM).
	TMT = Currency("TMT") // Turkmenistan manat (T).
	UZS = Currency("UZS") // Uzbekistani soʻm (soʻm, сум).
	AFN = Currency("AFN") // Afghan afghani (Af).
	JPY = Currency("JPY") // Japanese yen (¥).
	SGD = Currency("SGD") // Singapore dollar (S$).
	HKD = Currency("HKD") // Hong Kong dollar (HK$).
	KPW = Currency("KPW") // North Korean won (₩).
	KRW = Currency("KRW") // South Korean won (₩).
	MOP = Currency("MOP") // Macanese pataca (MOP$).
	TWD = Currency("TWD") // Taiwan new dollar (NT$).
	CNY = Currency("CNY") // Chinese onshore yuan renminbi (¥) traded within Mainland China only.
	CNH = Currency("CNH") // Chinese offshore yuan renminbi (¥) traded outside of Mainland China.
	INR = Currency("INR") // Indian rupee (₨, ₹, ৳, रु).
	NPR = Currency("NPR") // Nepalese rupee (रु, ₨).
	PKR = Currency("PKR") // Pakistani rupee (₨).
	MYR = Currency("MYR") // Malaysian ringgit (RM).
	PHP = Currency("PHP") // Philippine peso (₱).
	THB = Currency("THB") // Thai Baht (฿).
	IDR = Currency("IDR") // Indonesian rupiah (Rp).
	LAK = Currency("LAK") // Lao kip (₭, ₭N).
	BDT = Currency("BDT") // Bangladeshi taka (৳).
	BTN = Currency("BTN") // Bhutanese ngultrum (Nu.).
	CHR = Currency("CHR") // Cambodian riel (៛).
	LKR = Currency("LKR") // Sri Lankan rupee (Rs, රු, ரூ).
	MMK = Currency("MMK") // Myanmar kyat (K).
	VND = Currency("VND") // Vietnamese đồng (đ).
	MNT = Currency("MNT") // Mongolian tögrög (₮).
	SRD = Currency("SRD") // Surinamese dollar (Sr$).
	EGP = Currency("EGP") // Egyptian pound (£, E£, ج.م, L.E.).
	SAR = Currency("SAR") // Saudi riyal (SR, ر.س).
	AED = Currency("AED") // United Arab Emirates dirham (فلس).
	BHD = Currency("BHD") // Bahraini dinar (BD, د.ب).
	IQD = Currency("IQD") // Iraqi dinar (د.ع).
	IRR = Currency("IRR") // Iranian rial (﷼).
	JOD = Currency("JOD") // Jordanian dinar (JD, د.أ).
	KWD = Currency("KWD") // Kuwaiti dinar (KD, د.ك).
	LYD = Currency("LYD") // Libyan dinar (LD, ل.د).
	MAD = Currency("MAD") // Moroccan dirham (DH).
	OMR = Currency("OMR") // Omani rial (R.O., ر.ع.).
	QAR = Currency("QAR") // Qatari riyal (QR, ر.).
	YER = Currency("YER") // Yemeni rial (ر.ي, ﷼).
	SYP = Currency("SYP") // Syrian pound (LS, £S).
	LBP = Currency("LBP") // Lebanese pound (ل.ل.‎).
	ETB = Currency("ETB") // Ethiopian birr (Br, ብር).
	TND = Currency("TND") // Tunisian dinar (DT, د.ت).
	ARS = Currency("ARS") // Argentine peso ($).
	BRL = Currency("BRL") // Brazilian real (R$).
	CLP = Currency("CLP") // Chilean peso ($).
	CLF = Currency("CLF") // Unidad de Fomento (Chilean funds code, UF).
	MXN = Currency("MXN") // Mexican peso (Mex$).
	MXV = Currency("MXV") // Unidad de Inversion (Mexican funds code, UDI).
	BOB = Currency("BOB") // Bolivian boliviano (Bs).
	COP = Currency("COP") // Colombian peso ($).
	COU = Currency("COU") // Unidad de Valor Real (Colombian funds code, UVR).
	CRC = Currency("CRC") // Costa Rican colón (₡).
	CUC = Currency("CUC") // Cuban convertible peso ($, CUC or CUC$).
	CUP = Currency("CUP") // Cuban peso ($, $MN, or ₱).
	CVE = Currency("CVE") // Cape Verdean escudo ($, Esc).
	DOP = Currency("DOP") // Dominican peso ($, RD$).
	FJD = Currency("FJD") // Fijian dollar (FJ$).
	FKP = Currency("FKP") // Falkland Islands pound (£, FK£).
	GIP = Currency("GIP") // Gibraltar pound (£).
	GTQ = Currency("GTQ") // Guatemalan quetzal (Q).
	HNL = Currency("HNL") // Honduran lempira (L).
	HTG = Currency("HTG") // Haitian gourde (G).
	JMD = Currency("JMD") // Jamaican dollar ($).
	KYD = Currency("KYD") // Cayman Islands dollar (CI$).
	LRD = Currency("LRD") // Liberian dollar (L$, LD$).
	MGA = Currency("MGA") // Malagasy ariary (Ar).
	NIO = Currency("NIO") // Nicaraguan córdoba (C$).
	PAB = Currency("PAB") // Panamanian balboa (B/).
	PEN = Currency("PEN") // Peruvian sol (S/).
	PGK = Currency("PGK") // Papua New Guinean kina (K).
	PYG = Currency("PYG") // Paraguayan guaraní (₲).
	SBD = Currency("SBD") // Solomon Islands dollar ($, SI$).
	SCR = Currency("SCR") // Seychellois rupee (SR).
	SHP = Currency("SHP") // Saint Helena pound (£).
	SLL = Currency("SLL") // Sierra Leonean leone (Le).
	STN = Currency("STN") // São Tomé and Príncipe dobra (Db).
	SVC = Currency("SVC") // Salvadoran colón (₡).
	TOP = Currency("TOP") // Tongan paʻanga (T$).
	TTD = Currency("TTD") // Trinidad and Tobago dollar ($, TT$).
	UY1 = Currency("UY1") // Uruguay Peso en Unidades Indexadas (Funds code, URUIURUI).
	UYU = Currency("UYU") // Uruguayan peso ($, $U).
	UYW = Currency("UYW") // Unidad previsional, Uruguay.
	VES = Currency("VES") // Venezuelan bolívar (Bs.S, B$).
	VUV = Currency("VUV") // Vanuatu vatu (VT).
	WST = Currency("WST") // Samoan tālā ($, SAT, ST, T).
	XCD = Currency("XCD") // Eastern Caribbean dollar ($).
	XPF = Currency("XPF") // CFP franc (₣).
	ANG = Currency("ANG") // Netherlands Antillean guilder (NAƒ, NAf, ƒ, f).
	AWG = Currency("AWG") // Aruban florin (Afl, ƒ.).
	BBD = Currency("BBD") // Barbadian dollar ($, BBD$).
	BMD = Currency("BMD") // Bermudian dollar ($).
	BND = Currency("BND") // Brunei dollar ($, B$).
	BSD = Currency("BSD") // Bahamian dollar ($, B$).
	BZD = Currency("BZD") // Belize dollar ($).
	AOA = Currency("AOA") // Angolan kwanza (Kz).
	BIF = Currency("BIF") // Burundian franc (FBu).
	BWP = Currency("BWP") // Botswana pula (P).
	CDF = Currency("CDF") // Congolese franc (FC).
	DJF = Currency("DJF") // Djiboutian franc (Fdj).
	ERN = Currency("ERN") // Eritrean nakfa (Nkf, ናቕፋ, ناكفا).
	GHS = Currency("GHS") // Ghanaian cedi (GH₵).
	GMD = Currency("GMD") // Gambian dalasi (D).
	GNF = Currency("GNF") // Guinean franc (FG, GFr).
	GYD = Currency("GYD") // Guyanese dollar ($, G$, GY$).
	KES = Currency("KES") // Kenyan shilling (KSh, K).
	KMF = Currency("KMF") // Comorian franc (CF).
	LSL = Currency("LSL") // Lesotho loti (M).
	MRU = Currency("MRU") // Mauritanian ouguiya (UM).
	MUR = Currency("MUR") // Mauritian rupee (₨).
	MVR = Currency("MVR") // Maldivian rufiyaa (Rf, MRf, .ރ).
	MWK = Currency("MWK") // Malawian kwacha (K).
	MZN = Currency("MZN") // Mozambican metical (MT, MTn).
	NAD = Currency("NAD") // Namibian dollar ($, N$).
	NGN = Currency("NGN") // Nigerian naira (₦).
	RWF = Currency("RWF") // Rwandan franc (FRw, RF, R₣).
	SDG = Currency("SDG") // Sudanese pound (£SD, ج.س).
	SOS = Currency("SOS") // Somali shilling (Sh.So).
	SSP = Currency("SSP") // South Sudanese pound (SS£).
	SZL = Currency("SZL") // Swazi lilangeni (E).
	TZS = Currency("TZS") // Tanzanian shilling (TSh).
	UGX = Currency("UGX") // Ugandan shilling (USh).
	ZMW = Currency("ZMW") // Zambian kwacha (K, ZK).
	ZWL = Currency("ZWL") // Zimbabwean dollar ($, Z$).
	XOF = Currency("XOF") // West African CFA franc (CFA).
	XAG = Currency("XAG") // Silver (one troy ounce).
	XAU = Currency("XAU") // Gold (one troy ounce).
	XPD = Currency("XPD") // Palladium (one troy ounce).
	XPT = Currency("XPT") // Platinum (one troy ounce).
	XXX = Currency("XXX") // No currency. Used to denote a transaction involving no currency.
	XTS = Currency("XTS") // Code reserved for testing purposes.
	BTC = Currency("BTC") // Bitcoin (cryptocurrency, ₿).
	BCH = Currency("BCH") // Bitcoin Cash (cryptocurrency).
	XLM = Currency("XLM") // Stellar Lumen (cryptocurrency).
	XMR = Currency("XMR") // Monero (cryptocurrency).
	XRP = Currency("XRP") // Ripple (cryptocurrency).
	XTZ = Currency("XTZ") // Tez (cryptocurrency, ꜩ).
	DSH = Currency("DSH") // Dash (cryptocurrency).
	ETH = Currency("ETH") // Ethereum (cryptocurrency).
	ETC = Currency("ETC") // Ethereum Classic (cryptocurrency).
	LTC = Currency("LTC") // Litecoin (cryptocurrency, Ł).
	VTC = Currency("VTC") // Vertcoin (cryptocurrency).
	ZEC = Currency("ZEC") // Zcash (cryptocurrency).
	EOS = Currency("EOS") // EOS.IO (cryptocurrency).
)

//gocyclo:ignore
//nolint:funlen,cyclop,exhaustive
// Symbol returns a currency symbol to display.
func (c Currency) Symbol() string {
	switch c {
	case EUR:
		return "€"
	case USD:
		return "$"
	case USX:
		return "¢"
	case GBP:
		return "£"
	case GBX:
		return "p"
	case ZAR:
		return "R"
	case ZAC:
		return "c"
	case CHF:
		return "Fr"
	case CAD:
		return "C$"
	case AUD:
		return "A$"
	case DKK:
		return "kr"
	case SEK:
		return "kr"
	case NOK:
		return "kr"
	case ISK:
		return "Íkr"
	case CZK:
		return "Kč"
	case PLN:
		return "zł"
	case HUF:
		return "Ft"
	case RON:
		return "leu"
	case MDL:
		return "L"
	case RUB:
		return "₽"
	case UAH:
		return "₴"
	case BYR:
		return "Br"
	case BGN:
		return "лв"
	case BAM:
		return "KM"
	case HRK:
		return "kn"
	case MKD:
		return "ден"
	case RSD:
		return "дин"
	case ALL:
		return "L"
	case TRY:
		return "₺"
	case ILS:
		return "₪"
	case AMD:
		return "֏"
	case AZN:
		return "₼"
	case GEL:
		return "₾"
	case KGS:
		return "som"
	case KZT:
		return "₸"
	case TJS:
		return "SM"
	case TMT:
		return "T"
	case UZS:
		return "soʻm"
	case AFN:
		return "Af"
	case JPY:
		return "¥"
	case SGD:
		return "S$"
	case HKD:
		return "HK$"
	case KPW:
		return "₩"
	case KRW:
		return "₩"
	case MOP:
		return "MOP$"
	case TWD:
		return "NT$"
	case CNY:
		return "¥"
	case CNH:
		return "¥"
	case INR:
		return "₹"
	case NPR:
		return "रु"
	case PKR:
		return "₨"
	case MYR:
		return "RM"
	case PHP:
		return "₱"
	case THB:
		return "฿"
	case IDR:
		return "Rp"
	case LAK:
		return "₭"
	case BDT:
		return "৳"
	case BTN:
		return "Nu."
	case CHR:
		return "៛"
	case LKR:
		return "රු"
	case MMK:
		return "K"
	case VND:
		return "đ"
	case MNT:
		return "₮"
	case SRD:
		return "Sr$"
	case EGP:
		return "E£"
	case SAR:
		return "SR"
	case BHD:
		return "BD"
	case JOD:
		return "JD"
	case KWD:
		return "KD"
	case LYD:
		return "LD"
	case MAD:
		return "DH"
	case OMR:
		return "RO"
	case QAR:
		return "QR"
	case SYP:
		return "£S"
	case ETB:
		return "ብር"
	case TND:
		return "DT"
	case BRL:
		return "R$"
	case CLF:
		return "UF"
	case MXN:
		return "Mex$"
	case BOB:
		return "Bs"
	case CRC:
		return "₡"
	case CUC:
		return "CUC$"
	case CUP:
		return "$MN"
	case CVE:
		return "Esc"
	case DOP:
		return "RD$"
	case FJD:
		return "FJ$"
	case FKP:
		return "FK£"
	case GTQ:
		return "Q"
	case HNL:
		return "L"
	case HTG:
		return "G"
	case KYD:
		return "CI$"
	case LRD:
		return "L$"
	case MGA:
		return "Ar"
	case NIO:
		return "C$"
	case PAB:
		return "B/"
	case PEN:
		return "S/"
	case PGK:
		return "K"
	case PYG:
		return "₲"
	case SBD:
		return "SI$"
	case SCR:
		return "SR"
	case SLL:
		return "Le"
	case STN:
		return "Db"
	case SVC:
		return "₡"
	case TOP:
		return "T$"
	case TTD:
		return "TT$"
	case UYU:
		return "$U"
	case VES:
		return "Bs.S"
	case VUV:
		return "VT"
	case WST:
		return "ST"
	case XPF:
		return "₣"
	case ANG:
		return "NAƒ"
	case AWG:
		return "Afl"
	case BBD:
		return "BBD$"
	case AOA:
		return "Kz"
	case BIF:
		return "FBu"
	case BWP:
		return "P"
	case CDF:
		return "FC"
	case DJF:
		return "Fdj"
	case ERN:
		return "Nkf"
	case GHS:
		return "GH₵"
	case GMD:
		return "D"
	case GNF:
		return "GFr"
	case GYD:
		return "GY$"
	case KES:
		return "KSh"
	case KMF:
		return "CF"
	case LSL:
		return "M"
	case MRU:
		return "UM"
	case MUR:
		return "₨"
	case MVR:
		return "MRf"
	case MWK:
		return "K"
	case MZN:
		return "MT"
	case NAD:
		return "N$"
	case NGN:
		return "₦"
	case RWF:
		return "R₣"
	case SDG:
		return "£SD"
	case SOS:
		return "Sh.So"
	case SSP:
		return "SS£"
	case SZL:
		return "E"
	case TZS:
		return "TSh"
	case UGX:
		return "USh"
	case ZMW:
		return "ZK"
	case ZWL:
		return "Z$"
	case XOF:
		return "CFA"
	case BTC:
		return "₿"
	case XTZ:
		return "ꜩ"
	case LTC:
		return "Ł"
	default:
		return ""
	}
}

//nolint:gomnd,exhaustive
// Decimals returns the number of minor units (digits after the decimal separator).
func (c Currency) Decimals() int {
	switch c {
	case EUX, USX, GBX, ZAC, ISK, JPY, KRW, IDR, VND, CLP, UY1, VUV, WST, XPF, BIF:
		return 0
	case BHD, IQD, JOD, KWD, LYD, OMR:
		return 3
	case CLF, UYW, EOS:
		return 4
	case XAG, XAU, XPD, XPT:
		return 5
	case XRP, XTZ:
		return 6
	case BTC, BCH, XLM, DSH, LTC, VTC, ZEC:
		return 8
	case XMR:
		return 12
	case ETH, ETC:
		return 18
	default:
		return 2
	}
}

//nolint:exhaustive
// RoundString returns string representing an amount rounded to the number of minor units
// (digits after the decimal separator).
func (c Currency) RoundString(amount float64) string {
	switch c {
	case EUX, USX, GBX, ZAC, ISK, JPY, KRW, IDR, VND, CLP, UY1, VUV, WST, XPF, BIF:
		return fmt.Sprintf("%.0f", amount) // 0 decimals
	case BHD, IQD, JOD, KWD, LYD, OMR:
		return fmt.Sprintf("%.3f", amount) // 3 decimals
	case CLF, UYW, EOS:
		return fmt.Sprintf("%.4f", amount) // 4 decimals
	case XAG, XAU, XPD, XPT:
		return fmt.Sprintf("%.5f", amount) // 5 decimals
	case XRP, XTZ:
		return fmt.Sprintf("%.6f", amount) // 6 decimals
	case BTC, BCH, XLM, DSH, LTC, VTC, ZEC:
		return fmt.Sprintf("%.8f", amount) // 8 decimals
	case XMR:
		return fmt.Sprintf("%.12f", amount) // 12 decimals
	case ETH, ETC:
		return fmt.Sprintf("%.16f", amount) // 18 decimals
	default:
		return fmt.Sprintf("%.2f", amount)
	}
}
